//
// Created by bison on 4/3/19.
//

#ifndef GAME_MAPPED_INPUT_H
#define GAME_MAPPED_INPUT_H

#include <defs.h>

//typedef u32 MappedInputId;

enum {
    INPUT_ACTION_UP,
    INPUT_ACTION_DOWN,
    INPUT_ACTION_LEFT,
    INPUT_ACTION_RIGHT,
    INPUT_ACTION_ENTER,
    INPUT_ACTION_SPACE,
    INPUT_ACTION_ESCAPE,
    INPUT_ACTION_TOGGLE_FPS,
    INPUT_ACTION_TOGGLE_FREECAM,
    INPUT_ACTION_TOGGLE_EDIT,
    INPUT_ACTION_SELECT_WEAPON1,
    INPUT_ACTION_SELECT_WEAPON2,
    INPUT_ACTION_LMB_DOWN,
    INPUT_ACTION_LMB_UP,
    INPUT_ACTION_RMB_DOWN,
    INPUT_ACTION_RMB_UP,
    INPUT_ACTION_DEL,
    INPUT_ACTION_INS,
    INPUT_ACTION_TOOL_1,
    INPUT_ACTION_TOOL_2,
    INPUT_ACTION_TOOL_3,
    INPUT_ACTION_TOOL_4,
    INPUT_ACTION_TOOL_5,
    INPUT_ACTION_TOOL_6,
    INPUT_ACTION_SAVE,
    INPUT_ACTION_LOAD,
    INPUT_ACTION_DUPLICATE,
    INPUT_ACTION_HIDE,
    INPUT_ACTION_GRID,
};

enum {
    INPUT_STATE_FORWARD,
    INPUT_STATE_BACK,
    INPUT_STATE_LEFT,
    INPUT_STATE_RIGHT,
    INPUT_STATE_PUNCH,
    INPUT_STATE_KICK,
    INPUT_STATE_JUMP,
};

#endif //GAME_MAPPED_INPUT_H
